---
title: "Defining convention"
bibliography: ../../semantics.bib
---

### Defining convention via conceptual analysis

Lewis's goal in @lewis_languages_1975 is to understand what is involved when a community of language users knows a language.
Because he views language use in a community as the adoption by that community of a particular convention, he lays out a number of criteria that he thinks conventions, in general, ought to satisfy.
According to Lewis, any given habit or practice that persists within some community is a *convention* just in case the following hold:

1. Everyone conforms, i.e., participates in the habit.
2. Everyone believes the other members of the community conform.
3. The other members of the community conforming provides a reason to conform.
4. People generally prefer for the other members of the community to conform, rather than not conform.
5. The habit is optional or arbitrary, in the sense that it is selected from among some set of available alternative possible habits.
6. There is common knowledge within the community of the above criteria.
   That is, each community member knows (in some sense) about the convention, expects others to know about it, and expects others to have similar expectations.^[
   Including the expectation that others have similar expectations!
   ]

Here, Lewis is engaged in what's called *"conceptual analysis"*:
he takes an ordinary English expression (*convention*), which English speakers regularly use with, perhaps at best, an implicit understanding of how it is used, and he attempts to elaborate necessary and sufficient conditions for its application.
That is, Lewis takes conditions 1 through 6 to *define* the term *convention*.
They all have to hold (they are necessary), and *only* they have to hold (they are sufficient), in order for something to be a convention.
Why does he do this?
Well in part, because he thinks the criteria in 1 - 6 isolate and shed light on an interesting array of phenomena that exist among our species---driving on the right vs. left of the road (depending on where one lives), greeting people in a particular way, knocking on doors to request entry, and a zillion other things;
and in part, because as a philosopher of language, he thinks one of these kinds of phenomena---linguistic conventions---is particularly interesting.
Does *convention*, when understood as abbreviating the conditions 1 through 6, have the same meaning as the ordinary English word *convention*?
Maybe, maybe not.
It doesn't really matter very much for our purposes, since we just want a basic way of narrowing in on the phenomenon we're studying (language, communication, meaning, etc.), along with, perhaps, what important features it has in common with certain other practices that people engage in.

One of the candidate conventions we looked at was teeth-brushing.
I'll go through the criteria here to see how well they apply to this particular practice.

#### Brushing your teeth

1. It's true that not everyone conforms (or always conforms), but not conforming is often noticed or frowned upon---something which at least appears to be true of genuine conventions, in general.
2. With certain exceptions, people expect each other to conform;
   this case doesn't seem out of the ordinary for established conventions.
3. It is perhaps a little bit tricky to determine whether others brushing their teeth provides a reason for one to brush one's own teeth.
   On the one hand, the main reasons people brush their teeth are to help prevent cavities and to not have bad breath.
   On the other hand, not having bad breath---while (or *because*) people believe it makes interactions with other people more pleasant---is often *expected*.
   In fact, there might exist a standard in societies in which teeth-brushing is common, according to which people shouldn't be perceived as having bad breath;
   further, this standard may be reinforced when people actually do brush their teeth:
   the more people engage in the practice, the more social pressure there is to conform.
   If we entertain this possibility, it appears that other people brushing their teeth *can* provide a reason for one to brush one's own teeth.
4. There appears to be a general preference that people brush their teeth.
   For one, people are often concerned about others' hygiene because it affects their own experience (e.g., they don't want to smell someone else's bad breath).
   But also---insofar as standards of hygiene and cleanliness are perhaps somewhat arbitrary---I suspect people want to not have wasted their effort when they brush their *own* teeth.
   They might want their action to be justified, in part, by the existence of the standard.
   (Just think of how many people might stop brushing their teeth if the people around them stopped---probably at least a few?)
5. Whether or not teeth-brushing is optional or arbitrary may also seem tricky to determine.
   On the one hand, it might not be clear what other practice would allow people to keep their teeth clean;
   on the other hand, it is a bit clearer what alternative practice might allow members of a community to adhere to a communal standard:
   the practice of *not* brushing your teeth.
   That is, we would just have to change the standard, and suddenly, people would be relieved of the social pressure to brush one's teeth with which it coincides.
6. Insofar as the above observations are accurate, they appear to be common knowledge.
   Common enough, at least, that you might expect to hear a reminder if you go to the dentist.
   
I think there's a good argument that teeth-brushing is (sometimes) a convention:
it's a convention when the community in which it is done adopts a standard (e.g., having healthy teeth, not being perceived as having bad breath)---one that teeth-brushing helps people meet.
There might, of course, be other reasons to brush your teeth than the fact that it's a convention.

### Linguistic conventions

@lewis_languages_1975 claims that for a community to use a language is for it to adopt a certain convention involving that language.
First, he has an apparently bespoke definition of a *language*.

(@ex-language) A **language** is a set of pairs of forms and meanings.

He doesn't say too much about what meanings are here, but he invokes the concept of a *possible world* when he discusses the meanings of sentences.
Specifically, sentence meanings, for Lewis, are *sets* of possible worlds.
For any sentence $S$ in a language, a possible world is an element of the set paired up with $S$ by the language just in case $S$ is true at that world.
(For example, the English sentence 'there are dragons' would be true at a possible world in which there are only dragons;
it would also be true at a possible world in which there are both dragons and sea turtles.)

The convention that Lewis believes defines language use in a community is the following one (paraphrased):

(@ex-language-use) A population uses a language just in case there is a convention of truthfulness and trust in the language.
- Truthfulness:
  try to never utter sentences of the language that are not true (i.e., sentences that the language pairs up with sets of possible worlds which don't have the actual world as one of its elements).
- Trust:
  impute truthfulness to others;
  i.e., believe the things others tell you in the language.

In other words, a community can be said to use a language to communicate if it has a convention of uttering true sentences and believing that the sentences that other people utter are true.
As with other conventions, you can call someone out if they violate this convention ("How dare you lie to me! 😤").
