project:
  type: website
  output-dir: ../docs/slides
  render:
    - aug22/index.qmd

format:
  revealjs:
    theme: default
    highlight-style: gruvbox-dark
    slide-number: true
    chalkboard: true
    incremental: true
    preview-links: auto
    css: styles.css
    footer: "Introduction to Semantics"
