---
title: "Assignment"
bibliography: ../../semantics.bib
format:
  html:
    css: ../styles.css
    html-math-method: mathjax
    mathjax-config:
      loader: {load: ['[tex]/bussproofs','[tex]/bbox','[tex]/colorbox']}
      tex:
        packages: {'[+]': ['bussproofs','bbox','colorbox']}

---

::: {.hidden}
$$
\newcommand{\expr}[3]{\begin{array}{c}
#1 \\
\bbox[lightblue,5px]{#2}
\end{array} ⊢ #3}
\newcommand{\ct}[1]{\bbox[font-size: 0.8em]{\mathsf{#1}}}
\newcommand{\abbr}[1]{\bbox[transform: scale(0.95)]{\mathtt{#1}}}
\def\true{\ct{T}}
\def\false{\ct{F}}
$$
:::

Due on Wednesday, October 29th.

### Part 1

In the following exercise, I will describe the behavior of an expression in English---that is, what it can combine with, and what it makes as a result.
Based on my description, I want you to:

- say what its syntactic category is in "parentheses" notation;
- say what its syntactic category is in "tree" notation;
- say what its semantic type is, assuming the category-type correspondence discussed in [Syntactic categories](syn_types.html).
  You can use either the usual notation or the "tree" notation for semantic types in this part.

(1) This expression takes a transitive verb to its left, and then a noun phrase to its left, to form a sentence.

(2) This expression combines with a preposition to its right, and then a verb phrase to its left, to form a transitive verb.

(3) This expression combines with an expression $X$ to its right, where $X$ is something that takes a preposition on its left to form a verb phrase, and together with $X$, it forms a preposition.

### Part 2

Recall that in [A first approximation of English](../models/english.html) of the Models module, we assigned the connective *and* the category $con$ in order to account for sentences like (@ex-and).

(@ex-and) Ziggy runs and jumps.

Provide a new lexical entry for *and* that uses the syntactic category system defined in [Syntactic categories](syn_types.html).
Provide lexical entries for *runs* and *jumps* (including their meanings), and give a derivation of the sentence in (@ex-and).

### Part 3

Consider the following sentence, which features an adjective in predicate position.

(@ex-fast) Ziggy is fast.

Assume that there is a new base category for adjective phrases---call it $ap$---which is the syntactic category of the adjective *fast*.

What semantic type do you think this category should be associated with?
Keep in mind that this semantic type doesn't have to be $e$ or $t$---it can be something more complex!

What syntactic category should the copula *is* have?
Given this syntactic category, what is the semantic type of *is*?
