---
title: "Conventional implicatures versus presuppositions"
bibliography: ../../semantics.bib
---

### Disappearing presuppositions

One well-studied feature of presuppositions is that, despite the fact that they tend to project, they can also be canceled (or sometimes, modified) under certain circumstances.
For example, consider the following cases, in which sentences that normally display presuppositions are made the consequent clauses of certain conditional sentences:

(@ex-def-conditional) If Bo has a dog, he brought [the dog]{.gb-orange} to his place of work.

(@ex-love-conditional) If Jo is actually good at Go, she [loves]{.gb-orange} that she's good at Go.

In (@ex-def-conditional), a sentence that entails *there is a dog*---the usual presupposition of the consequent clause---is the antecedent of the conditional.
In (@ex-love-conditional), the sentence which is usually the presupposition of the consequent clause is made the antecedent of the conditional.
In each case, the entire conditionals themselves don't appear to have the relevant presuppositions:
(@ex-def-conditional), taken as a whole, does *not* imply that there is a dog;
nor does (@ex-love-conditional) imply that Jo is good at Go.

We obtain a similar pattern if we conjoin the antecedent sentences of these conditionals with the corresponding consequent sentences, and then negate the coordinate structure that result:

(@ex-def-negated) It's not true that Bo has a dog and that he brought [the dog]{.gb-orange} to his place of work.

(@ex-love-conditional) It's not true that Jo is good at Go and that she [loves]{.gb-orange} that she's good at Go.

### Conventional implicatures project

Like presuppositions, conventional implicatures show projection behavior when subjected to family-of-sentence tests.
Consider the example in (@ex-nrrc), which features a conventional implicature triggered by a non-restrictive relative clause.

(@ex-nrrc) The class is taught by Julian[, who enjoys syntax]{.gb-red}.

This sentence implies that Julian enjoys syntax.
Like a presupposition, this inference appears to project under negation:

(@ex-nrrc-negated) The class isn't taught by Julian[, who enjoys syntax]{.gb-red}.

Same with questioning the sentence and placing it into the antecedent of a conditional, which you can check.

What's notable about conventional implicatures is that if you try to cancel them using means similar to those described above, the result is a bit odd:

(@ex-nrrc-conditional) \#If Julian enjoys syntax, then the class is taught by Julian[, who enjoys syntax]{.gb-red}.

This sounds weird, suggesting that the conventional implicature is forced to project;
that is, what may make this conditional sentence odd is that it triggers the inference that Julian enjoys syntax---due to the non-restrictive relative clause---while at the same time, the fact that *Julian enjoys syntax* is the antecedent the conditional may trigger an ignorance implicature, i.e., that the utterer doesn't know whether or not Julian enjoys syntax.
So, on the one hand, the utterer believes Julian enjoys syntax (i.e., the conventional implicature), while on the other hand, they are conversationally implicating that they don't know whether or not he does.
(Or something along those lines :).)

The point here is that this apparent difference between presuppositions and conversational implicatures can provide a kind of test that helps distinguish between them.
For a given candidate presupposition or conventional implicature $S$, ask yourself, "Can I place $S$ into the consequent of a conditional sentence in the way described above, so that it is canceled?"
If so, you may have a presupposition.
If not (because the result is weird), you may have a conventional implicature.
