---
title: "Overview"
bibliography: ../../semantics.bib
---

The data we tend to be interested in in semantics is inference judgment data.
We can view an inference as being a pair of expressions of the language (or *utterances* of such expressions)---$E_{1}$ and $E_{2}$---where $E_{2}$ is generally a declarative sentence.
In that case, we can ask if using $E_{1}$ triggers an inference that $E_{2}$ is true.
If it does, then we say that $E_{2}$ is an inference of $E_{1}$ (or of an utterance of $E_{1}$).

We have four kinds of inference that we'd like to be able to classify.
These are:

- entailments
- conversational implicatures
- presuppositions
- conventional implicatures

Each of these kinds of inference can itself be viewed as a relation between expressions, or utterances of expressions.
For example, we can say that sentence 1 *entails* sentence 2, or that it conversationally implicates it.
Strictly speaking, it is really an *utterance* of a sentence that triggers a conversational implicature---one wherefrom it is assumed that the person making the utterance is following certain conversational principles---but linguists often say that a sentence $S$ triggers a conversational implicature as a shorthand to mean that utterances of $S$ tend to give rise to the implicature.

Likewise, expressions of different syntactic categories can presuppose certain sentences, or they can conventionally implicate them.
