---
title: "Applying the maxims"
bibliography: ../../semantics.bib
---

@grice_logic_1975 gives several examples of inferences that appear to result from the maxims, given particular utterances.
These inferences are called *conversational implicatures*.
Here, I'll give a few of my own.

### Manner

Here's one:

(@ex-manner-1) Bo walked to his desk, sat down, and got up.

This sentence, when uttered, appears to imply that Bo first walked to his desk, then sat down, and then got up, rather than that he might have done these things in some other order.
(That said, people tend to say that (@ex-manner-1) is still *true*, even if he did do them in another order.)
This inference might be viewed as arising from the maxim of Manner, insofar as this maxim prescribes that the order in which predicates describing events are conjoined should mirror the order in which the events described are implied to have transpired.

Why would the maxim of Manner prescribe this?
Not totally obvious, perhaps;
but one idea might be that understanding an event description involves, in some sense, constructing a mental representation of the event which is being described.
And it might be easier for people to update mental representations of sequences of events with new events that are hypothesized to occur *later* in time than any events already in the sequence than it is for people to update such sequences with new events that are hypothesized to occur earlier in time than some events already in the sequence.
If this is true, and people (implicitly) know that it is true, then they might try to make their utterances easier to understand, in view of this general fact.
That is, they might try to utter event descriptions in an order that allows people to more easily update their existing mental representation with a representation of a new event.

To be sure, this is mostly word vomit and should be spelled out---ideally in terms of some precise cognitive architecture and theory of language processing (e.g., stated in the [ACT-R](http://act-r.psy.cmu.edu/) framework).

### Quantity

Here's an example which appears to rely on Quantity:

(@ex-quantity) Jo did some of the readings.

An utterance of this sentence seems to imply that Jo did not do all of the readings.
One might reason about why this inference is produced as follows:

 1. If the speaker is following the Maxim of Quantity, and if they believe that Jo did all of the readings, then they should say that Jo did all of the readings.^[
	Meanwhile, the Maxim of Quality dictates that the speaker should say that Jo did all of the readings *only if* they believe it to be true.
	Thus even if Quantity produces a preference for 'all' over 'some', this preference can only be indulged if Quality isn't violated in the process.
 ]
 2. The speaker didn't say that Jo did all of the readings.
 3. Therefore (by 1 and 2), either (a) the speaker isn't following the Maxim of Quantity, or (b) it isn't the case that they believe that Jo did all of the readings.
 4. Because of Grice's Cooperative Principle, we should assume that the speaker is following the Maxim of Quantity.
 5. Therefore (by 3 and 4), it isn't the case that the speaker believes that Jo did all of the readings.

At this point, we've said enough to derive the inference that *it is not the case that* the speaker thinks that Jo did all of the readings.
If we additionally assume that the speaker is opinionated on this matter---i.e., either they believe Jo did all of the readings or they believe Jo didn't do all of the readings---then we can derive the conversational implicature---specifically, a *scalar* or *quantity* implicature---that (the speaker believes that) Jo didn't do all of the readings.
If instead, we concluded that the speaker doesn't have enough evidence to use *all* instead of *some*---i.e., that they aren't necessarily opinionated---then one would conclude that there is an intended *ignorance implicature*:
the speaker doesn't know whether or not Jo did all of the readings, which is why they opted for the weaker *some*.

Note that this situation seems to differ slightly from one in which Bo makes the utterance in (@ex-ignorance).

(@ex-ignorance) Jo: What do you want? <br>
	Bo: Something with a lot of caffeine.
	
Here, we don't get the inference, say, that Bo doesn't want a matcha latte, or that Bo doesn't want a cappuccino, both of which would entail that he wants something with a lot of caffeine, and which therefore constitute stronger statements.
Instead, we seem to observe an ignorance implicature;
i.e., that *Bo doesn't know what he wants* (he knows only that it should contain caffeine).

### Relation

Recall the interaction in which Jo and Bo are outside a coffee shop, looking in through the window.

(@ex-relation) Jo: There's no one at the cash register. <br>
	Bo: The lights are on.
	
Here, it's easy to draw the inference that Jo thinks the coffee shop might be closed, as well as the inference that Bo thinks it might be open.
We might use Relation to help explain these inferences if we assume that Jo and Bo are addressing the question of whether or not the coffee shop is open and, hence, are attempting to make utterances which are relevant to this question.
If so, then Jo can be understood as offering up evidence for the coffee shop being closed, while Bo can be seen as providing evidence that it is open.
