project:
  type: website
  output-dir: ../docs/notes

website:
  title: "Probabilistic dynamic semantics"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
    - about.qmd
    - index.qmd

format:
  html:
    theme: [lux,tufte]
    highlight-style: gruvbox-dark
    css: styles.css
    toc: true
    code-tools: true

# filters:
  # - line-highlight
