project:
  type: website
  output-dir: ../docs/notes

website:
  title: "Introduction to semantics"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
    - about.qmd
    - index.qmd
    - section: "Convention"
      contents:
        - convention/defining_convention.qmd
        - convention/defining_meaning.qmd
        - convention/assignment.qmd
    - section: "Speech acts"
    - section: "Speaker meaning"
      contents:
        - speaker_meaning/maxims.qmd
        - speaker_meaning/applying_maxims.qmd
    - section: "Diagnosing inference"
      contents:
        - diagnosing_inference/overview.qmd
        - diagnosing_inference/entailment.qmd
        - diagnosing_inference/conversational_implicature.qmd
        - diagnosing_inference/presupposition.qmd
        - diagnosing_inference/conventional_implicature.qmd
        - diagnosing_inference/assignment.qmd
    - section: "Formal preliminaries"
    - section: "Theories of meaning"
    - section: "Models"
    - section: "Applicative categorial grammar"
    - section: "Verbs"
    - section: "Coordinators"
    - section: "Adjectives"
    - section: "Pronouns"
    - section: "Quantification"

format:
  html:
    theme: [lux,tufte]
    highlight-style: gruvbox-dark
    css: styles.css
    toc: true
    code-tools: true

# filters:
  # - line-highlight
