---
title: "Syllabus"
bibliography: ../semantics.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/chicago-author-date.csl
---

Welcome to Intro to Semantics!^[Listed as both LIN4803 and LIN6804 at [one.uf.edu](https://one.uf.edu/).]

I'm [Julian Grove](https://juliangrove.github.io/) - I'm an Assistant Professor in the [Linguistics Department](https://lin.ufl.edu/) (where this course is offered).

Here is my contact info:

- Office: 4108 Turlington
- Phone: 352.294.7456
- Email: first name dot last name at ufl dot edu
- Office hours: Mondays, 1pm-2pm and by appointment

Check out the [About](/about.html) page for more info about me and this site.

Here are some facts about this course:

- It takes place in [Matherly](https://campusmap.ufl.edu/#/index/0406) 0115.
- It happens on Mondays, Wednesdays, and Fridays.
- It runs from 10:40am - 11:30am.

## Bird's-eye view

The goals of this course are to acquaint you with the study of meaning in natural language;
specifically, to equip you with a certain vocabulary of concepts, as well as a certain collection of theoretical and methodological tools.
This vocabulary and these tools will allow you to:

- collect linguistic data and determine whether and how it is relevant to meaning;
- formulate and test hypotheses and theoretical claims about linguistic meaning; and
- approach questions about how linguistic meaning is situated within the broader scientific study of natural language and the human mind.

The first few weeks of the course will be more-or-less stage setting.
Natural language semantics is a young field whose basic aims and guiding principles are somewhat in flux;
so it will be useful to have this part of the course be dedicated to making these aims and principles fairly explicit.
After these introductory weeks, we will get deep into the practice of doing semantics by focusing on a variety of empirical phenomena.
The main acts will be verbs and their arguments, coordination, modification, anaphora, and quantification.

## Attendance and class participation

Come to class!
You're likely to do better in the course if you come than if you don't.

When you're here, participate!
You'll get more out of the class if you do, and it'll be more fun.

## Assignments and grading

### Grading

Your work in this course will consist of [nine (9) short written assignments]{.underline}---sometimes based on assigned readings---as well as an [in-person final exam]{.underline}.
Each written assignments will be a collection of responses to questions:
some of these responses will have a mini-essay format, and some will be more like answers to problem sets (it'll be clear in any given case what the expectation is).
Each assignment will be available on this site, at the end of the set of notes to which the assignment corresponds.
Please either turn in a physical copy of your responses the beginning of the class on which the assignment is due, or upload them to Canvas before class starts.

The written assignments will be graded on a 100-point scale, using the following rough rubric:

- 81-100: you thoroughly engage with each question on the assignment.
  This means that you justify each of your responses, as well point out its implications, if appropriate.
  For example, if the truth of your response is likely to have any unintuitive consequences, you should note and explain these.
  Doing this well will sometimes be challenging and require you to think a lot.
  
  If the assignment has questions requiring the application of analytical techniques that we have introduced in the course, "thorough engagement", for current purposes, means applying these techniques in the right way.
- 61-80: you thoroughly engage with most, but not all, of the questions.
- 41-60: you thoroughly engage with only a small part of the assignment and give shallow or cursory answers to most of it.
- 21-40: you give shallow or cursory answers to all of the questions on the assignment.
- 1-20: you barely do the assignment.
- 0: you don't even barely do the assignment.

The assignments themselves will have a more precise points breakdown.

The written assignments will account for 90% of your grade, and the final exam, for 10%.
The final will take place from 3pm-5pm on December 8th (place TBD).
It will be formatted similarly to the assignments.

The following grading scale will be used to determine course grades:

|                  |                  |                  |
|------------------|------------------|------------------|
| 93.5 ≤ A ≤ 100   | 89.5 ≤ A- < 93.5 |                  |
| 86.5 ≤ B+ < 89.5 | 83.5 ≤ B < 86.5  | 79.5 ≤ B- < 83.5 |
| 76.5 ≤ C+ < 79.5 | 74.5 ≤ C < 76.5  | 69.5 ≤ C < 74.5  |
| 66.5 ≤ D+ < 69.5 | 64.5 ≤ D < 66.5  | 59.5 ≤ D- < 64.5 |

### Collaboration (including with chatbots)

We'll talk about this in class.
Basically:

- Actually do the readings yourself.
- Complete the assignments yourself.
- If you worked with someone else in the class (or a chatbot) on an assignment, please indicate that you did.
  If you used a chatbot, include a note with your assignment describing how you used it.
  Please specify:
  - the prompt you used;
  - the output that the model produced.

### Missed or late work

Late work will be docked 10 points each day it is late.
It will not be accepted once it is four days late.
If you need an extension, ask for one---just do it prior to the due date.

### Extra credit

If you like, you can get extra credit, accounting for up to an additional 2% of your course grade, in one of two ways:

1. You can earn up to two credits by participating in linguistics studies through the Linguistics Department's SONA account (so, one percentage point of your grade per credit).
   [This document](https://docs.google.com/document/d/1e2P7ubMYnsfhV9Ycj47kc8niPRBPAyhh/edit?tab=t.0) has more information;
   so does [this video](https://mediasite.video.ufl.edu/Mediasite/Play/7f3d951f0471439387079e4096f08a591d).
   If you go this route, please participate in the studies before November 22.
2. You can read and summarize the main arguments of a (short) semantics paper, i.e., published in a journal, collection, or conference proceedings.
   Here are some paper suggestions (which I will continue to add to during the semester), but note that you can also summarize a paper of your choosing, so long as you consult with me about it first.
   
   - @glass_attested_2025
   - @karttunen_implicative_1971
   - @klecha_diagnosing_2014
   - @steinert-threlkeld_semantic_2023

## Zulip

There is a Zulip site for this course at [uf-semantics-2026.zulipchat.com](https://uf-semantics-2026.zulipchat.com/).
All communication about the course should be done through Zulip.
For example, rather than email me, please send me a message there.
We'll also use Zulip to host discussions of the course material.
You can post (and answer!) questions there.
(I may chime in, as well.)

## University Honesty Policy

UF students are bound by The Honor Pledge which states, "We, the members of the University of Florida community, pledge to hold ourselves and our peers to the highest standards of honor and integrity by abiding by the Honor Code."
On all work submitted for credit by students at the University of Florida, the following pledge is either required or implied:
"On my honor, I have neither given nor received unauthorized aid in doing this assignment."
The Honor Code ([policy.ufl.edu/regulation/4-040/](https://policy.ufl.edu/regulation/4-040/)) specifies a number of behaviors that are in violation of this code and the possible sanctions.
Furthermore, you are obligated to report any condition that facilitates academic misconduct to appropriate personnel.
If you have any questions or concerns, please consult with the instructor.

## Counseling and Wellness Center

Contact information for the Counseling and Wellness Center:

- [counseling.ufl.edu](http://www.counseling.ufl.edu/)
- Phone: 352.392.1575

Contact information for the University Police Department:

- [police.ufl.edu](https://police.ufl.edu/contact/)
- Phone: 352.392.1111

## Accommodations for Students with Disabilities

Students with disabilities requesting accommodations should first register with the Disability Resource Center (352.392.8565, [disability.ufl.edu](https://disability.ufl.edu/)) by providing appropriate documentation.
Once registered, students will receive an accommodation letter which must be presented to the instructor when requesting accommodation.
Students with disabilities should follow this procedure as early as possible in the semester.

## Academic polices and resources

Available here:

- [syllabus.ufl.edu/syllabus-policy/uf-syllabus-policy-links/](https://syllabus.ufl.edu/syllabus-policy/uf-syllabus-policy-links/)

## Calendar

| Date           | Topic                                    | Reading                                                           | Assignment |
|----------------|------------------------------------------|-------------------------------------------------------------------|------------|
| Fri., Aug. 21  | Introduction                             |                                                                   |            |
| Mon., Aug. 24  | Convention                               | @lewis_languages_1975 (pp. 3--10)                                 |            |
| Wed., Aug. 26  | Convention                               | @grice_meaning_1957                                               | View       |
| Fri., Aug. 28  | Speech acts                              | @bach_speech_2006 (pp. 147--155)                                  |            |
| Mon., Aug. 31  | Speech acts                              |                                                                   |            |
| Wed., Sept. 2  | Speaker meaning                          | @grice_logic_1975                                                 |            |
| Fri., Sept. 4  | Speaker meaning                          |                                                                   |            |
| Wed., Sept. 9  | Diagnosing inference                     | @winter_elements_2016 (Ch. 2, pp. 12--16)                         |            |
| Fri., Sept. 11 | Diagnosing inference                     | @coppock_invitation_2025 (Ch. 1, pp. 13--41; Ch. 8, pp. 315--322) | View       |
| Mon., Sept. 14 | Sets and set theory                      |                                                                   |            |
| Wed., Sept. 16 | Functions, relations, and languages      |                                                                   |            |
| Fri., Sept. 18 | No class: Julian away                    |                                                                   |            |
| Mon., Sept. 21 | Models                                   | @winter_elements_2016 (Ch. 2, pp. 17--27)                         | View       |
| Wed., Sept. 23 | Arabic numeral arithmetic                |                                                                   |            |
| Fri., Sept. 25 | Intransitive verbs                       | @winter_elements_2016 (Ch. 3, pp. 44--64)                         |            |
| Mon., Sept. 28 | Intransitive verbs                       | @winter_elements_2016 (Ch. 3, pp. 64-72)                          |            |
| Wed., Sept. 30 | What should go into a theory of meaning? | @bach_meaning_2006; @szabo_compositionality_2020 (§§3--4)         | View       |
| Fri., Oct. 2   | Lambda notation and types                |                                                                   |            |
| Mon., Oct. 5   | Lambda notation and types                |                                                                   |            |
| Wed., Oct. 7   | Transitive verbs                         |                                                                   |            |
| Mon., Oct. 12  | Transitive verbs                         |                                                                   |            |
| Wed., Oct. 14  | Applicative categorial grammar           | @jurafsky_speech_2025 (Appendix E)                                |            |
| Fri., Oct. 16  | No class: Julian away                    |                                                                   |            |
| Mon., Oct. 19  | Grammars and models                      |                                                                   | View       |
| Wed., Oct. 21  | Verbs and arguments redux                |                                                                   |            |
| Fri., Oct. 23  | Verbs and arguments redux                |                                                                   |            |
| Mon., Oct. 26  | Coordinators                             | @winter_elements_2016 (Ch. 3, pp. 74--80)                         |            |
| Wed., Oct. 28  | Coordinators                             |                                                                   | View       |
| Fri., Oct. 30  | Adjectives                               | @kennedy_adjectives_2012                                          |            |
| Mon., Nov. 2   | Adjectives                               |                                                                   |            |
| Wed., Nov. 4   | Adjectives                               |                                                                   | View       |
| Fri., Nov. 6   | Pronouns                                 |                                                                   |            |
| Mon., Nov. 9   | Pronouns                                 |                                                                   |            |
| Fri., Nov. 13  | Pronouns                                 |                                                                   |            |
| Mon., Nov. 16  | Quantifiers                              | @winter_elements_2016 (Ch. 4, pp. 99--108)                        | View       |
| Wed., Nov. 18  | Quantifiers                              |                                                                   |            |
| Fri., Nov. 20  | Quantifiers                              |                                                                   |            |
| Mon., Nov. 30  | Negative polarity items                  |                                                                   | View       |
| Wed., Dec. 2   | Quantifiers and scope                    |                                                                   |            |
