---
title: "Overview"
bibliography: ../../semantics.bib
format:
  html:
    css: ../styles.css
    html-math-method: mathjax
    mathjax-config:
      loader: {load: ['[tex]/bussproofs','[tex]/bbox','[tex]/colorbox']}
      tex:
        packages: {'[+]': ['bussproofs','bbox','colorbox']}

---

::: {.hidden}
$$
\newcommand{\expr}[3]{\begin{array}{c}
#1 \\
\bbox[lightblue,5px]{#2}
\end{array} ⊢ #3}
\newcommand{\ct}[1]{\bbox[font-size: 0.8em]{\mathsf{#1}}}
\newcommand{\abbr}[1]{\bbox[transform: scale(0.95)]{\mathtt{#1}}}
\def\true{\ct{T}}
\def\false{\ct{F}}
$$
:::

These notes aim to get a better handle on the syntax and semantics of coordinators, like *and* and *or*.
Something special about coordinators, at least in English, is their apparent ability to coordinate expressions of any category.
For example, while we can coordinate sentences and verb phrases, like in (@ex-and-or-s-vp)

(@ex-and-or-s-vp) a. Po slept {and, or} Tigress jumped.
	a. Po slept {and, or} jumped.
	
we can also coordinate noun phrases, transitive verbs, intransitive verbs, prepositional phrases, and perhaps even other categories like prepositions, like in (@ex-and-or-others).

(@ex-and-or-others) a. Po {and, or} Tigress slept.
	b. Tigress punched {and, or} helped Po.
	c. Po cooked noodles in the kitchen {and, or} for Tigress.
	d. Po cooked noodles inside {and, or} outside the kitchen.

Not only is it possible to coordinate strings of various categories, but when we do, a systematic pattern of inference seems arise.
When we coordinate constituents smaller than sentences, what's produced is a sentence which seems to *mean the same thing* as a sentence-level coordination.
For example, the sentence in (@ex-and-or-s-vp\-a) appears to mean the same thing as the sentence in (@ex-and-or-others\-a) when the same coordinator occurs in both---or at least the two sentences entail each other.

A similar situation holds for the other uses of *and* and *or*.
For example (@ex-and-or-others\-b-d) appear to be in a mutual-entailment relation with the sentences in (@ex-and-or-rephrased\-a-c), respectively.

(@ex-and-or-rephrased) a. Tigress punched Po {and, or} Tigress helped Po.
	b. Po cooked noodles in the kitchen {and, or} Po cooked noodles for Tigress.
	c. Po cooked noodles inside the kitchen {and, or} Po cooked noodles outside the kitchen.
	
How can we explain this?
