---
title: "Assignment"
bibliography: ../../semantics.bib
format:
  html:
    css: ../styles.css
    html-math-method: mathjax
    mathjax-config:
      loader: {load: ['[tex]/bussproofs','[tex]/bbox','[tex]/colorbox']}
      tex:
        packages: {'[+]': ['bussproofs','bbox','colorbox']}

---

::: {.hidden}
$$
\newcommand{\expr}[3]{\begin{array}{c}
#1 \\
\bbox[lightblue,5px]{#2}
\end{array} ⊢ #3}
\newcommand{\ct}[1]{\bbox[font-size: 0.8em]{\mathsf{#1}}}
\newcommand{\abbr}[1]{\bbox[transform: scale(0.95)]{\mathtt{#1}}}
\def\True{\ct{T}}
\def\False{\ct{F}}
$$
:::

Due on Monday, October 13th.

### Part 1

According to the collection of syntactic rules provided [here](ana_semantics.html) in (5) (with semantics) and [here](ana_syntax.html) in (2) (without semantics), the $np$ $⌜537⌝$ is syntactically ambiguous.
Either (a) $⌜5⌝$ combines with $⌜3⌝$ first, and then $⌜53⌝$ combines with $⌜7⌝$;
or (b) $⌜3⌝$ and $⌜7⌝$ combine, and then $⌜37⌝$ combines with $⌜5⌝$.
Example 1 in our [examples](ana_examples.html) shows the second way of doing things, where $⌜37⌝$ combines with $⌜5⌝$.

Show the first way.
Does doing things the first way change the interpretation?

### Part 2

There is a planet orbiting [Proxima Centauri](https://en.wikipedia.org/wiki/Proxima_Centauri) that has a population of organisms which are very human-like.
As it happens, a group within the larger population uses a system a lot like Arabic numeral arithmetic to perform arithmetic calculations, except that the syntax and semantics are slightly different.
This group uses a base-7 number system, and the atomic numerals have different meanings than they do in Arabic numeral arithmetic.
We can call the language they use for arithmetic calculations $L_{NANA}$ (not Arabic numeral arithmetic).

To be more precise, for this group within the population which lives on the planet orbiting Proxima Centauri,^[
	It really exists!
] the set of *atomic* numerals is the following one:

$$atom = \{⌜1⌝, ⌜2⌝, ⌜3⌝, ⌜4⌝, ⌜5⌝, ⌜6⌝, ⌜7⌝\}$$

Meanwhile, the interpretation function of the model employed by this group, $I_{NANA}$, is the following:

$$I_{NANA}(⌜1⌝) = 6$$
$$I_{NANA}(⌜2⌝) = 5$$
$$I_{NANA}(⌜3⌝) = 4$$
$$I_{NANA}(⌜4⌝) = 3$$
$$I_{NANA}(⌜5⌝) = 2$$
$$I_{NANA}(⌜6⌝) = 1$$
$$I_{NANA}(⌜7⌝) = 0$$

The full model of $L_{NANA}$ employed by this group is thus:

$$\mathcal{M}_{NANA} = ⟨ℕ, \{\True, \False\}, I_{NANA}⟩$$

One more thing.
Instead of the Rule 3 which we defined [here](ana_semantics.html), these guys use the following *alternative* Rule 3:

\begin{prooftree}
\AxiomC{$⟨x, ⟦x⟧_{\mathcal{M}_{ANA}}⟩ ⊢ n$}
\AxiomC{$⟨y, ⟦y⟧_{\mathcal{M}_{ANA}}⟩ ⊢ n$}
\RightLabel{Rule 3}\BinaryInfC{$⟨x^{⌢}y, ⟦x⟧_{\mathcal{M}_{ANA}} * 7^{length(y)} + ⟦y⟧_{\mathcal{M}_{ANA}}⟩ ⊢ n$}
\end{prooftree}

The rules of for generating strings of $L_{NANA}$ and their interpretations are otherwise identical to those for generating strings of $L_{ANA}$ and their interpretations.

Show that $⌜((53 + 6) × 5) = 24⌝$ is a sentence (i.e., an $s$) of $L_{NANA}$, and show what its interpretation is.

### Part 3

Using the English grammar fragment defined [here](english.html) in conjunction with the model defined [here](english_examples.html), show that the string in (@ex-bella) is a sentence (i.e., an $s$), and show what its interpretation is.

(@ex-bella) Bella doesn't jump and run.
